/*
 * Sample REST Server
 *
 * TODO
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateTask",
		strings.ToUpper("Post"),
		"/task/",
		CreateTask,
	},

	Route{
		"DeleteAllTasks",
		strings.ToUpper("Delete"),
		"/task/",
		DeleteAllTasks,
	},

	Route{
		"DeleteTask",
		strings.ToUpper("Delete"),
		"/task/{id}",
		DeleteTask,
	},

	Route{
		"GetAllTasks",
		strings.ToUpper("Get"),
		"/task/",
		GetAllTasks,
	},

	Route{
		"GetByDueDate",
		strings.ToUpper("Get"),
		"/due/{year}/{month}/{day}",
		GetByDueDate,
	},

	Route{
		"GetTask",
		strings.ToUpper("Get"),
		"/task/{id}",
		GetTask,
	},

	Route{
		"GetTasksByTag",
		strings.ToUpper("Get"),
		"/tag/{tagname}",
		GetTasksByTag,
	},
}
